<?php
//TODO: add comments
 ?>
 <?php if (Mage::helper('Gigya_Social')->isPluginEnabled('gigya_reactions/gigya_reactions_conf')) : ?>
 <?php
  $product = $this->getProduct();
  $desc = ($product->getShortDescription() !== NULL) ? $product->getShortDescription() : $product->getDescription();
  $ua = Mage::helper('core')->jsonEncode(array(
    'title'       => $product->getName(),
    'description' => $this->stripTags($desc),
    'linkBack'    => $product->getProductUrl(),
    'imageUrl'    => $product->getImageUrl(),
  ));
  $settings = Mage::helper('Gigya_Social')->getPluginConfig('gigya_reactions/gigya_reactions_conf', 'php', TRUE);
  $settings['barID'] = $product->getSku();
  ?>
  <script type="text/javascript">//<![CDATA[
    var gigyaSettings = gigyaSettings || {};
    gigyaSettings.reactions = <?php echo  Mage::helper('core')->jsonEncode($settings) ?>;
    gigyaSettings.reactions.ua = <?php echo $ua ?>
    //]]>
  </script>
  <div id="<?php echo Mage::helper('Gigya_Social')->getPluginContainerId('gigya_reactions/gigya_reactions_conf') ?>" class="gigya-reactions"></div>
  <?php endif ?>

