<?php
//TODO: add comments
 ?>
 <?php if (Mage::helper('Gigya_Social')->isShareBarEnabled('cart')) : ?>
 <?php
  $product = $this->getProduct();
  $desc = ($product->getShortDescription() !== NULL) ? $product->getShortDescription() : $product->getDescription();
  $ua = Mage::helper('core')->jsonEncode(array(
    'title'       => $product->getName(),
    'description' => $this->stripTags($desc),
    'linkBack'    => $product->getProductUrl(),
    'imageUrl'    => $product->getImageUrl()
  ));
  ?>
  <script type="text/javascript">//<![CDATA[
    var gigyaSettings = gigyaSettings || {};
    gigyaSettings.sharebar = <?php echo Mage::helper('Gigya_Social')->getPluginConfig('gigya_share/gigya_sharebar')  ?>;
    gigyaSettings.sharebar.ua = <?php echo $ua ?>
    //]]>
  </script>
  <div id="<?php echo Mage::helper('Gigya_Social')->getPluginContainerId('gigya_share/gigya_sharebar') ?>" class="gigya-sharebar" style="margin-bottom: 10px;"></div>
  <?php endif ?>

