<?php
/**
 * Retrieve the sharebar settings set in admin
 * parse settings to json object
 * add the parameters to gigyaSettings js object.
 * print the gigyaSettings.sharebar settings object to front end.
 *
 */

$config = Mage::getStoreConfig('gigya_followbar/gigya_followbar_conf');
// set buttons json
$buttons = json_decode($config['buttons']);
$config['buttons'] = $buttons;
// set advanced config json
$config_json = configToJson($config);

/*
 * Extract advanced params array if exists from config
 * add them to config array
 * transform complete config to gigya json format
 *
 * @param array $config
 * @return json $config_json
 */
function configToJson($config) {
  if ($config['advancedConfig']) {
    $advanced = json_decode($config['advancedConfig'], true);
    $config = array_merge($config, $advanced);
    unset($config['advancedConfig']);
  }
  return $config_json = json_encode($config);
}

?>
<script type="text/javascript">//<![CDATA[
  var gigyaSettings = gigyaSettings || {};
  gigyaSettings.followbar = <?php echo $config_json ?>;
  //]]>
</script>
<div id="<?php echo Mage::helper('Gigya_Social')->getPluginContainerId('gigya_followbar/gigya_followbar_conf'); ?>" class="gigya-followbar" style="margin-bottom: 10px;"></div>

<!--
/* default buttons template:

[
  {
  "provider": "facebook",
  "actionURL": "https://www.facebook.com/gigya",
  "action": "dialog"
  },
  {
  "provider": "twitter",
  "followUsers": "gigya, gigyaDev",
  "action": "dialog"
  },
  {
  "provider": "googleplus",
  "actionURL": "https://plus.google.com/107788669599113247501/posts",
  "action": "window"
  },
  {
  "provider": "linkedin",
  "actionURL": "http://www.linkedin.com/company/gigya",
  "action": "window"
  },
  {
  "provider": "rss",
  "actionURL": "http://blog.gigya.com/feed/",
  "action": "window"
  },
  {
  "provider": "email",
  "confirmationText":"Thank you for following us",
  "action": "dialog"
  }
*/
-->