<?php
/**
 * Retrieve the sharebar settings set in admin
 * parse settings to json object
 * add the parameters to gigyaSettings js object.
 * print the gigyaSettings.sharebar settings object to front end.
 *
 */
// set advanced config json
$plugin_conf = 'gigya_followbar/gigya_followbar_conf';
if (Mage::helper('Gigya_Social')->isPluginEnabled($plugin_conf)) :

  $config = Mage::helper('Gigya_Social')->getPluginConfig($plugin_conf, 'php');
  // set buttons json
  $buttons = json_decode($config['buttons']);
  $config['buttons'] = $buttons;

  $params = Mage::helper('core')->jsonEncode($config);

  ?>
  <script type="text/javascript">//<![CDATA[
    var gigyaSettings = gigyaSettings || {};
    gigyaSettings.followbar = <?php echo $params ?>;
    //]]>
  </script>
  <div id="<?php echo Mage::helper('Gigya_Social')->getPluginContainerId($plugin_conf); ?>" class="gigya-followbar" style="margin-bottom: 10px;"></div>

<?php endif ?>

<!--
/* default buttons template:

[
  {
  "provider": "facebook",
  "actionURL": "https://www.facebook.com/gigya",
  "action": "dialog"
  },
  {
  "provider": "twitter",
  "followUsers": "gigya, gigyaDev",
  "action": "dialog"
  },
  {
  "provider": "googleplus",
  "actionURL": "https://plus.google.com/107788669599113247501/posts",
  "action": "window"
  },
  {
  "provider": "linkedin",
  "actionURL": "http://www.linkedin.com/company/gigya",
  "action": "window"
  },
  {
  "provider": "rss",
  "actionURL": "http://blog.gigya.com/feed/",
  "action": "window"
  },
  {
  "provider": "email",
  "confirmationText":"Thank you for following us",
  "action": "dialog"
  }
*/
-->