<?php
  $product = $this->getProduct();
  $parms = Mage::helper('Gigya_Social')->getPluginConfig('gigya_r_and_r/gigya_r_and_r_conf', 'php');
   unset($parms['enable']);
   $parms['streamID'] = $product->getSku();
   $parms['context']['reviewUrl'] = $this->getReviewsUrl();
   $parms['containerID'] = $parms['containerID'] . '-' . $product->getId();
?>
      <script type="text/javascript">//<![CDATA[
        var gigyaSettings = gigyaSettings || {};
        gigyaSettings.ratings = gigyaSettings.ratings || [];
        gigyaSettings.ratings.push(<?php echo Mage::helper('core')->jsonEncode($parms) ?>);
        //]]>
      </script>
    <div id="<?php echo $parms['containerID'] ?>" class="ratings-short">
        <?php if ($this->getRatingSummary()):?>
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
            </div>
        <?php endif;?>
        <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='<?php echo $this->getReviewsUrl() ?>'; return false;"><?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?></a></span>
    </div>
