<?php
$userMode = Mage::getStoreConfig('gigya_login/gigya_user_management/login_modes');
?>
<?php if ($userMode === 'social') : ?>
    <script type="text/javascript">//<![CDATA[
        gigyaMageSettings.login =
        <?php echo Mage::helper('Gigya_Social')->getPluginConfig('gigya_login/gigya_login_conf')  ?>
        //]]>
    </script>
    <div id="<?php echo Mage::helper('Gigya_Social')->getPluginContainerId('gigya_login/gigya_login_conf') ?>"
         class="gigya-login"></div>
<?php endif ?>
<?php if ($userMode === 'raas') : ?>
<script type="text/javascript">//<![CDATA[
    gigyaMageSettings.RaaS =
    <?php echo Mage::helper('Gigya_Social')->getPluginConfig('gigya_login/gigya_raas_conf'); ?>
    //]]>
</script>
<?php endif ?>
