<?php if (Mage::helper('Gigya_Social')->isPluginEnabled('gigya_login/gigya_login_conf')) : ?>
<script type="text/javascript">//<![CDATA[
  var gigyaSettings = gigyaSettings || {};
  gigyaSettings.login = <?php echo Mage::helper('Gigya_Social')->getPluginConfig('gigya_login/gigya_login_conf')  ?>
  //]]>
</script>
<div id="<?php echo Mage::helper('Gigya_Social')->getPluginContainerId('gigya_login/gigya_login_conf') ?>" class="gigya-login"></div>
<?php endif ?>
